GET http://localhost:3003/countries/all
Content-Type: application/json

###

GET http://localhost:3003/countries/1
Content-Type: application/json


###

GET http://localhost:3003/countries/search?name=Bra
Content-Type: application/json


###

PUT http://localhost:3003/countries/edit/1
Content-Type: application/json

{
    "name":"",
    "capital":""
}

###

DEL http://localhost:3003/countries/:id
Content-Type: application/json

###

POST http://localhost:3003/countries/create
Content-Type: application/json